%Plantas%
planta_medicinal(agar-agar).
planta_medicinal(brionia).
planta_medicinal(helecho_macho).
planta_medicinal(monacillo).
planta_medicinal(acedera).
planta_medicinal(aceite_de_bacalao).
planta_medicinal(aceite_de_oliva).
planta_medicinal(acelga).
planta_medicinal(achicoria).
planta_medicinal(aconito).
planta_medicinal(aguacate).
planta_medicinal(aguante).
planta_medicinal(ajenjo).
planta_medicinal(ajo).
planta_medicinal(albahaca).
planta_medicinal(alcachofa).
planta_medicinal(alcanfor).
planta_medicinal(alfalfa).
planta_medicinal(alholva).
planta_medicinal(alpiste).
planta_medicinal(anacahuite).
planta_medicinal(anagalide).
planta_medicinal(anis).
planta_medicinal(anis_estrella).
planta_medicinal(apio).
planta_medicinal(arnica).
planta_medicinal(arroz).
planta_medicinal(artemisa).
planta_medicinal(avena).
planta_medicinal(azafran).
planta_medicinal(azahar).
planta_medicinal(belenio).
planta_medicinal(belladona).
planta_medicinal(benjui).
planta_medicinal(berro).
planta_medicinal(boldo).
planta_medicinal(borraja).
planta_medicinal(brionia).
planta_medicinal(cabellos_de_elote).
planta_medicinal(cacahuate).
planta_medicinal(calendula).
planta_medicinal(canela).
planta_medicinal(capulin).
planta_medicinal(cardo).
planta_medicinal(cascara_sagrada).
planta_medicinal(castaño_de_indias).
planta_medicinal(cebada).
planta_medicinal(cebolla).
planta_medicinal(cedro).
planta_medicinal(cedron).
planta_medicinal(cerezo).
planta_medicinal(chaparro_amargoso).
planta_medicinal(chia).
planta_medicinal(chicalote).
planta_medicinal(cilantro).
planta_medicinal(cipres).
planta_medicinal(ciruela).
planta_medicinal(clavo).
planta_medicinal(cola_de_caballo).
planta_medicinal(colchico).
planta_medicinal(coquito_de_aceite).
planta_medicinal(crataegus).
planta_medicinal(cuachalalate).
planta_medicinal(cuasia).
planta_medicinal(damiana).
planta_medicinal(diente_de_leon).
planta_medicinal(digital).
planta_medicinal(doradilla).
planta_medicinal(encina).
planta_medicinal(encino).
planta_medicinal(encino_rojo).
planta_medicinal(enebro).
planta_medicinal(epazote).
planta_medicinal(esparrago).
planta_medicinal(espinacas).
planta_medicinal(espinilla).
planta_medicinal(espino).
planta_medicinal(estafiate).
planta_medicinal(eucalipto).
planta_medicinal(fenogreco).
planta_medicinal(fresno).
planta_medicinal(gelsemio).
planta_medicinal(genciana).
planta_medicinal(germen_de_trigo).
planta_medicinal(gexanio).
planta_medicinal(girasol).
planta_medicinal(gobernadora).
planta_medicinal(gordolobo).
planta_medicinal(grama).
planta_medicinal(granada).
planta_medicinal(guayaba).
planta_medicinal(hamamelis).
planta_medicinal(helecho).
planta_medicinal(hiedra).
planta_medicinal(hierba_de_pollo).
planta_medicinal(higuera).
planta_medicinal(hinojo).
planta_medicinal(hisopo).
planta_medicinal(ipecacuana).
planta_medicinal(jengibre).
planta_medicinal(jugo_de_limon).
planta_medicinal(jugo_de_toronja).
planta_medicinal(jugo_de_vastago_de_platano_morado).
planta_medicinal(laurel).
planta_medicinal(lavanda).
planta_medicinal(leche_de_higuera).
planta_medicinal(lechuga).
planta_medicinal(limon).
planta_medicinal(linaza).
planta_medicinal(lino).
planta_medicinal(llanten).
planta_medicinal(lupulo).
planta_medicinal(malva).
planta_medicinal(malvavisco).
planta_medicinal(manzanilla).
planta_medicinal(marrubio).
planta_medicinal(mastuerzo).
planta_medicinal(matarique).
planta_medicinal(mate).
planta_medicinal(melisa).
planta_medicinal(membrillo).
planta_medicinal(menta).
planta_medicinal(mezquite).
planta_medicinal(miel).
planta_medicinal(milenrama).
planta_medicinal(mostaza).
planta_medicinal(muerdago).
planta_medicinal(muicle).
planta_medicinal(naranja).
planta_medicinal(nogal).
planta_medicinal(nuez_de_kola).
planta_medicinal(nuez_vomica).
planta_medicinal(ocote).
planta_medicinal(oregano).
planta_medicinal(ortiga).
planta_medicinal(papaloquelite).
planta_medicinal(papaya).
planta_medicinal(pasiflora).
planta_medicinal(perejil).
planta_medicinal(pimiento).
planta_medicinal(pingüica).
planta_medicinal(pino).
planta_medicinal(pirul).
planta_medicinal(prodigiosa).
planta_medicinal(puerco).
planta_medicinal(quina).
planta_medicinal(quina_amarilla).
planta_medicinal(quina_roja).
planta_medicinal(rabano).
planta_medicinal(raiz_de_granado_agrio).
planta_medicinal(retama).
planta_medicinal(ricino).
planta_medicinal(roble).
planta_medicinal(romero).
planta_medicinal(rosa).
planta_medicinal(rosal).
planta_medicinal(ruda).
planta_medicinal(ruibarbo).
planta_medicinal(sabina).
planta_medicinal(salvia).
planta_medicinal(sanguinaria).
planta_medicinal(sauco).
planta_medicinal(savia).
planta_medicinal(semilla_de_calabaza).
planta_medicinal(siempreviva).
planta_medicinal(sineonillo).
planta_medicinal(tabachin).
planta_medicinal(tabaco).
planta_medicinal(tabaquillo).
planta_medicinal(tamarindo).
planta_medicinal(te_limon).
planta_medicinal(te_negro).
planta_medicinal(tecomazuchil).
planta_medicinal(tejocote).
planta_medicinal(tila).
planta_medicinal(tilo).
planta_medicinal(tlachichinole).
planta_medicinal(toloache).
planta_medicinal(tomillo).
planta_medicinal(tornillo).
planta_medicinal(toronja).
planta_medicinal(toronjil).
planta_medicinal(tronadora).
planta_medicinal(uva).
planta_medicinal(valeriana).
planta_medicinal(verbena).
planta_medicinal(violeta).
planta_medicinal(yerbabuena).
planta_medicinal(yohimbo).
planta_medicinal(zanahoria).
planta_medicinal(zarzamora).
planta_medicinal(zarzaparrilla).
planta_medicinal(zoapatle).

planta_medicinal(mangle).

%Malestares%
malestar(abscesos).
malestar(absceso_hepatico).
malestar(acidez_estomacal).
malestar(acido_urico).
malestar(acne).
malestar(aftas).
malestar(agotamiento).
malestar(agruras).
malestar(albuminuria).
malestar(alcoholismo).
malestar(almorranas).
malestar(anemia).
malestar(anginas).
malestar(anorexia).
malestar(arteriosclerosis).
malestar(artritis).
malestar(asma).
malestar(atonia_estomacal).
malestar(bazo).
malestar(boca_inflamacion).
malestar(boca_estomatitis).
malestar(bronquitis).
malestar(bronconeumonia).
malestar(caida_del_cabello).
malestar(calambres).
malestar(calculos_biliares).
malestar(calculos_renales).
malestar(callos).
malestar(caries).
malestar(caspa).
malestar(cancer_del_utero).
malestar(ciatica).
malestar(circulacion).
malestar(cistitis).
malestar(colicos).
malestar(colitis).
malestar(contusiones).
malestar(tonico_para_el_corazon).
malestar(depurativos_de_la_sangre).
malestar(diabetes).
malestar(diarrea_cronica).
malestar(diarrea_por_irritacion).
malestar(diarrea_por_inflamacion).
malestar(diarrea_verdosa).
malestar(diarrea_con_sangre).
malestar(difteria).
malestar(disenteria).
malestar(dispepsia).
malestar(si_hay_dolor).
malestar(dolores_musculares).
malestar(empacho).
malestar(enteritis).
malestar(epilepsia).
malestar(epistaxis).
malestar(erisipela).
malestar(escarlatina).
malestar(estreñimiento).
malestar(faringitis).
malestar(flatulencias).
malestar(flebitis).
malestar(flemas).
malestar(forunculos).
malestar(gastralgia).
malestar(gonorrea).
malestar(gota).
malestar(grietas_del_ano).
malestar(grietas_del_pezon).
malestar(gripe).
malestar(halitosis).
malestar(hemorragia_interna).
malestar(hepatitis).
malestar(hernia).
malestar(herpes).
malestar(heridas).
malestar(hidropesia).
malestar(higado_congestion).
malestar(higado_colicos).
malestar(higado_bilis).
malestar(higado_ictericia).
malestar(hipertension).
malestar(hipotension).
malestar(hipo).
malestar(histerismo).
malestar(insomnio).
malestar(intestino_atonia).
malestar(impotencia_sexual).
malestar(jaqueca).
malestar(lactancia).
malestar(laringitis).
malestar(leucorrea).
malestar(lombrices).
malestar(lumbago).
malestar(llagas).
malestar(malaria).
malestar(menstruacion_abundante).
malestar(menstruacion_dolorosa).
malestar(menstruacion_escasa).
malestar(menstruacion_irregular).
malestar(metrorragia).
malestar(muelas).
malestar(muelas).
malestar(nariz).
malestar(nauseas).
malestar(neuralgias).
malestar(neurastenia).
malestar(nefritis).
malestar(obesidad).
malestar(oidos).
malestar(ojos).
malestar(paludismo).
malestar(pecas).
malestar(pies_olorosos).
malestar(piquetes_de_abeja).
malestar(piquetes_de_araña).
malestar(piquetes_de_mosco).
malestar(piquetes_de_vibora).
malestar(pleuresia).
malestar(piorrea).
malestar(prostata).
malestar(pulmonia).
malestar(quemaduras).
malestar(raquitismo).
malestar(reumatismo).
malestar(riñones).
malestar(ronquera).
malestar(sabañones).
malestar(san_vito).
malestar(sarampion).
malestar(sarna).
malestar(sarpullido).
malestar(sed).
malestar(solitaria).
malestar(sudoracion_excesiva).
malestar(tifoidea).
malestar(tiña).
malestar(tos).
malestar(tos_ferina).
malestar(tuberculosis).
malestar(ulcera).
malestar(urticaria).
malestar(varices).
malestar(vejiga).
malestar(verrugas).
malestar(vertigos).
malestar(vomitos).
malestar(voz).
malestar(falta_de_vitaminas).

%La planta X se usa para tratar el malestar Y%
tratamiento(malva,abscesos).
tratamiento(zarzaparrilla,absceso_hepatico).
tratamiento(anis,acidez_estomacal).
tratamiento(perejil,acidez_estomacal).
tratamiento(sanguinaria,acido_urico).
tratamiento(limon,acido_urico).
tratamiento(sauco,acido_urico).
tratamiento(arnica,acne).
tratamiento(llanten,aftas).
tratamiento(fenogreco,aftas).
tratamiento(zarzamora,aftas).
tratamiento(salvia,agotamiento).
tratamiento(tilo,agotamiento).
tratamiento(valeriana,agotamiento).
tratamiento(yerbabuena,agruras).
tratamiento(manzanilla,agruras).
tratamiento(jugo_de_limon,agruras).
tratamiento(jugo_de_toronja,agruras).
tratamiento(pingüica,albuminuria).
tratamiento(quina_roja,albuminuria).
tratamiento(encino_rojo,albuminuria).
tratamiento(pimiento,alcoholismo).
tratamiento(salvia,almorranas).
tratamiento(hamamelis,almorranas).
tratamiento(sanguinaria,almorranas).
tratamiento(cola_de_caballo,almorranas).
tratamiento(arnica,almorranas).
tratamiento(sauco,almorranas).
tratamiento(ajenjo,anemia).
tratamiento(germen_de_trigo,anemia).
tratamiento(quina,anemia).
tratamiento(canela,anemia).
tratamiento(alholva,anemia).
tratamiento(eucalipto,anginas).
tratamiento(cebada,anginas).
tratamiento(salvia,anginas).
tratamiento(tabachin,anginas).
tratamiento(borraja,anginas).
tratamiento(ajenjo,anorexia).
tratamiento(gerciana,anorexia).
tratamiento(yerbabuena,anorexia).
tratamiento(limon,arteriosclerosis).
tratamiento(genciana,arteriosclerosis).
tratamiento(cardo,arteriosclerosis).
tratamiento(zarzaparrilla,arteriosclerosis).
tratamiento(arnica,arteriosclerosis).
tratamiento(chicalote,arteriosclerosis).
tratamiento(alcanfor,arteriosclerosis).
tratamiento(toronja,arteriosclerosis).
tratamiento(limon,artritis).
tratamiento(genciana,artritis).
tratamiento(cardo,artritis).
tratamiento(zarzaparrilla,artritis).
tratamiento(arnica,artritis).
tratamiento(chicalote,artritis).
tratamiento(alcanfor,artritis).
tratamiento(toronja,artritis).
tratamiento(eucalipto,asma).
tratamiento(marrubio,asma).
tratamiento(toloache,asma).
tratamiento(oregano,asma).
tratamiento(salvia,asma).
tratamiento(lupulo,atonia_estomacal).
tratamiento(eucalipto_,atonia_estomacal).
tratamiento(cuasia,atonia_estomacal).
tratamiento(uva,bazo).
tratamiento(cerezo,bazo).
tratamiento(malva,boca_inflamacion).
tratamiento(rosal,boca_inflamacion).
tratamiento(limon,boca_inflamacion).
tratamiento(salvia,boca_inflamacion).
tratamiento(rosal,boca_estomatitis).
tratamiento(encina,boca_estomatitis).
tratamiento(salvia,boca_estomatitis).
tratamiento(zarzamora,boca_estomatitis).
tratamiento(eucalipto,bronquitis).
tratamiento(borraja,bronquitis).
tratamiento(anacahuite,bronquitis).
tratamiento(gordolobo,bronquitis).
tratamiento(tilo,bronquitis).
tratamiento(benjui,bronquitis).
tratamiento(marrubio,bronquitis).
tratamiento(rabano,bronquitis).
tratamiento(gordolobo,bronconeumonia).
tratamiento(eucalipto,bronconeumonia).
tratamiento(ipecacuana,bronconeumonia).
tratamiento(mostaza,bronconeumonia).
tratamiento(ortiga,caida_del_cabello).
tratamiento(espinilla,caida_del_cabello).
tratamiento(marrubio,caida_del_cabello).
tratamiento(romero,caida_del_cabello).
tratamiento(anis,calambres).
tratamiento(tila,calambres).
tratamiento(manzanilla,calambres).
tratamiento(ajenjo,calambres).
tratamiento(diente_de_leon,calculos_biliares).
tratamiento(aceite_de_oliva,calculos_biliares).
tratamiento(retama,calculos_biliares).
tratamiento(cabellos_de_elote,calculos_renales).
tratamiento(pingüica,calculos_renales).
tratamiento(cola_de_caballo,calculos_renales).
tratamiento(ajo,callos).
tratamiento(cebolla,callos).
tratamiento(hiedra,caries).
tratamiento(cola_de_caballo,caries).
tratamiento(ortiga,caspa).
tratamiento(limon,caspa).
tratamiento(romero,caspa).
tratamiento(cuachalalate,cancer_del_utero).
tratamiento(llanten,cancer_del_utero).
tratamiento(siempreviva,cancer_del_utero).
tratamiento(mastuerzo,ciatica).
tratamiento(higuera,ciatica).
tratamiento(sauco,ciatica).
tratamiento(toronjil,circulacion).
tratamiento(sanguinaria,circulacion).
tratamiento(salvia,circulacion).
tratamiento(hamamelis,circulacion).
tratamiento(cola_de_caballo,cistitis).
tratamiento(doradilla,cistitis).
tratamiento(ajo,cistitis).
tratamiento(cabellos_de_elote,cistitis).
tratamiento(menta,colicos).
tratamiento(hinojo,colicos).
tratamiento(manzanilla,colicos).
tratamiento(toronjil,colicos).
tratamiento(boldo,colicos).
tratamiento(linaza,colitis).
tratamiento(anis,colitis).
tratamiento(romero,colitis).
tratamiento(cola_de_caballo,colitis).
tratamiento(arnica,contusiones).
tratamiento(hamamelis,contusiones).
tratamiento(laurel,contusiones).
tratamiento(brionia,contusiones).
tratamiento(digital,tonico_para_el_corazon).
tratamiento(salvia,tonico_para_el_corazon).
tratamiento(nuez_de_kola,tonico_para_el_corazon).
tratamiento(tejocote,tonico_para_el_corazon).
tratamiento(achicoria,depurativos_de_la_sangre).
tratamiento(diente_de_leon,depurativos_de_la_sangre).
tratamiento(apio,depurativos_de_la_sangre).
tratamiento(sanguinaria,depurativos_de_la_sangre).
tratamiento(zarzaparrilla,depurativos_de_la_sangre).
tratamiento(berro,depurativos_de_la_sangre).
tratamiento(matarique,diabetes).
tratamiento(tronadora,diabetes).
tratamiento(eucalipto,diabetes).
tratamiento(damina,diabetes).
tratamiento(capulin,diarrea_cronica).
tratamiento(mezquite,diarrea_cronica).
tratamiento(tlachichinole,diarrea_cronica).
tratamiento(linaza,diarrea_por_irritacion).
tratamiento(membrillo,diarrea_por_irritacion).
tratamiento(arroz,diarrea_por_irritacion).
tratamiento(cebada,diarrea_por_irritacion).
tratamiento(guayaba,diarrea_por_inflamacion).
tratamiento(albahaca,diarrea_por_inflamacion).
tratamiento(granada,diarrea_por_inflamacion).
tratamiento(manzanilla,diarrea_verdosa).
tratamiento(sineonillo,diarrea_verdosa).
tratamiento(siempreviva,diarrea_verdosa).
tratamiento(chaparro_amargoso,diarrea_con_sangre).
tratamiento(muicle,diarrea_con_sangre).
tratamiento(monacillo,diarrea_con_sangre).
tratamiento(limon,difteria).
tratamiento(naranja,difteria).
tratamiento(tamarindo,disenteria).
tratamiento(chaparro_amargoso,disenteria).
tratamiento(ipecacuana,disenteria).
tratamiento(cedron,disenteria).
tratamiento(anis,dispepsia).
tratamiento(menta,dispepsia).
tratamiento(yerbabuena,dispepsia).
tratamiento(diente,dispepsia).
tratamiento(te_limon,dispepsia).
tratamiento(quina,dispepsia).
tratamiento(genciana,dispepsia).
tratamiento(tabaquillo,dispepsia).
tratamiento(ruibarbo,dispepsia).
tratamiento(anis_estrella,si_hay_dolor).
tratamiento(valeriana,si_hay_dolor).
tratamiento(manzanilla,si_hay_dolor).
tratamiento(alcanfor,dolores_musculares).
tratamiento(tamarindo,empacho).
tratamiento(linaza,enteritis).
tratamiento(cedron,enteritis).
tratamiento(llanten,enteritis).
tratamiento(valeriana,epilepsia).
tratamiento(hierba_de_pollo,epistaxis).
tratamiento(cebolla,epistaxis).
tratamiento(perejil,epistaxis).
tratamiento(sauco,erisipela).
tratamiento(hiedra,erisipela).
tratamiento(zanahoria,erisipela).
tratamiento(ajo,escarlatina).
tratamiento(limon,escarlatina).
tratamiento(berro,escarlatina).
tratamiento(cebolla,escarlatina).
tratamiento(gexanio,escarlatina).
tratamiento(ciruela,estreñimiento).
tratamiento(linaza,estreñimiento).
tratamiento(chia,estreñimiento).
tratamiento(tamarindo,estreñimiento).
tratamiento(agar-agar,estreñimiento).
tratamiento(eucalipto,faringitis).
tratamiento(lavanda,faringitis).
tratamiento(anacahuite,faringitis).
tratamiento(apio,flatulencias).
tratamiento(tomillo,flatulencias).
tratamiento(perejil,flatulencias).
tratamiento(anis_estrella,flatulencias).
tratamiento(hinojo,flatulencias).
tratamiento(torojil,flatulencias).
tratamiento(romero,flatulencias).
tratamiento(ruibarbo,flatulencias).
tratamiento(ruda,flatulencias).
tratamiento(menta,flatulencias).
tratamiento(arnica,flebitis).
tratamiento(alfalfa,flebitis).
tratamiento(lino,flebitis).
tratamiento(malvavisco,flebitis).
tratamiento(romero,flebitis).
tratamiento(quina,flebitis).
tratamiento(genciana,flemas).
tratamiento(oregano,flemas).
tratamiento(fenogreco,forunculos).
tratamiento(malvavidco,forunculos).
tratamiento(hiedra,forunculos).
tratamiento(manzanilla,gastralgia).
tratamiento(anis_estrella,gastralgia).
tratamiento(cola_de_caballo,gonorrea).
tratamiento(doradilla,gonorrea).
tratamiento(zarzaparrilla,gonorrea).
tratamiento(apio,gota).
tratamiento(cerezo,gota).
tratamiento(limon,gota).
tratamiento(pino,gota).
tratamiento(alcanfor,gota).
tratamiento(aconito,gota).
tratamiento(belladora,gota).
tratamiento(beleño,gota).
tratamiento(colchico,gota).
tratamiento(chicalote,gota).
tratamiento(encina,grietas_del_ano).
tratamiento(encina,grietas_del_pezon).
tratamiento(nogal,grietas_del_pezon).
tratamiento(milenrama,grietas_del_pezon).
tratamiento(eucalipto,gripe).
tratamiento(limon,gripe).
tratamiento(quina,gripe).
tratamiento(zarzaparrilla,gripe).
tratamiento(calendula,gripe).
tratamiento(hinojo,halitosis).
tratamiento(menta,halitosis).
tratamiento(mastuerzo,hemorragia_interna).
tratamiento(ortiga,hemorragia_interna).
tratamiento(rosal,hemorragia_interna).
tratamiento(retama,hepatitis).
tratamiento(boldo,hepatitis).
tratamiento(alcachofa,hepatitis).
tratamiento(prodigiosa,hepatitis).
tratamiento(cascara_sagrada,hepatitis).
tratamiento(helecho,hernia).
tratamiento(ricino,hernia).
tratamiento(tabaco,hernia).
tratamiento(linaza,herpes).
tratamiento(llanten,herpes).
tratamiento(arnica,heridas).
tratamiento(hamamelis,heridas).
tratamiento(alcachofa,hidropesia).
tratamiento(cedro,hidropesia).
tratamiento(perejil,hidropesia).
tratamiento(sauco,hidropesia).
tratamiento(berros,hidropesia).
tratamiento(retama,hidropesia).
tratamiento(marrubio,higado_congestion).
tratamiento(boldo,higado_congestion).
tratamiento(doradilla,higado_congestion).
tratamiento(ruibarbo,higado_congestion).
tratamiento(manzanilla,higado_colicos).
tratamiento(lechuga,higado_bilis).
tratamiento(tila,higado_bilis).
tratamiento(papaloquelite,higado_ictericia).
tratamiento(achicoria,higado_ictericia).
tratamiento(berros,higado_ictericia).
tratamiento(llanten,higado_ictericia).
tratamiento(retama,higado_ictericia).
tratamiento(tecomazuchil,higado_ictericia).
tratamiento(ajo,hipertension).
tratamiento(esparrago,hipertension).
tratamiento(alpiste,hipertension).
tratamiento(muerdago,hipertension).
tratamiento(miel,hipotension).
tratamiento(nuez_de_kola,hipotension).
tratamiento(crataegus,hipotension).
tratamiento(acedera,hipotension).
tratamiento(anis,hipo).
tratamiento(hinojo,hipo).
tratamiento(tila,hipo).
tratamiento(valeriana,hipo).
tratamiento(azahar,histerismo).
tratamiento(beleño,histerismo).
tratamiento(gelsemio,histerismo).
tratamiento(tila,histerismo).
tratamiento(valeriana,histerismo).
tratamiento(pasiflora,insomnio).
tratamiento(azahar,insomnio).
tratamiento(menta,insomnio).
tratamiento(manzanilla,insomnio).
tratamiento(lechuga,insomnio).
tratamiento(tila,insomnio).
tratamiento(genciana,intestino_atonia).
tratamiento(melisa,intestino_atonia).
tratamiento(yohimbo,impotencia_sexual).
tratamiento(damiana,impotencia_sexual).
tratamiento(nuez_vomica,impotencia_sexual).
tratamiento(aguacate,impotencia_sexual).
tratamiento(manzanilla,jaqueca).
tratamiento(aconito,jaqueca).
tratamiento(valeriana,jaqueca).
tratamiento(tila,jaqueca).
tratamiento(chicalote,jaqueca).
tratamiento(hinojo,lactancia).
tratamiento(anis,lactancia).
tratamiento(menta,lactancia).
tratamiento(perejil,lactancia).
tratamiento(zanahoria,lactancia).
tratamiento(aconito,laringitis).
tratamiento(borraja,laringitis).
tratamiento(cebolla,laringitis).
tratamiento(rosa,laringitis).
tratamiento(benjui,laringitis).
tratamiento(encino,laringitis).
tratamiento(encina,leucorrea).
tratamiento(zarzaparrilla,leucorrea).
tratamiento(pino,leucorrea).
tratamiento(enebro,leucorrea).
tratamiento(genciana,leucorrea).
tratamiento(ajenjo,lombrices).
tratamiento(ajo,lombrices).
tratamiento(cebolla,lombrices).
tratamiento(brionia,lombrices).
tratamiento(aguante,lombrices).
tratamiento(papaya,lombrices).
tratamiento(epazote,lombrices).
tratamiento(avena,lumbago).
tratamiento(cebada,lumbago).
tratamiento(tomillo,lumbago).
tratamiento(verbena,lumbago).
tratamiento(fenogreco,llagas).
tratamiento(eucalipto,llagas).
tratamiento(llanten,llagas).
tratamiento(sanguinaria,llagas).
tratamiento(quina,malaria).
tratamiento(girasol,malaria).
tratamiento(eucalipto,malaria).
tratamiento(cardo,malaria).
tratamiento(azafran,menstruacion_abundante).
tratamiento(hamamelis,menstruacion_abundante).
tratamiento(belladona,menstruacion_dolorosa).
tratamiento(anis_estrella,menstruacion_dolorosa).
tratamiento(ruda,menstruacion_escasa).
tratamiento(ajenjo,menstruacion_escasa).
tratamiento(manzanilla,menstruacion_escasa).
tratamiento(apio,menstruacion_irregular).
tratamiento(hisopo,menstruacion_irregular).
tratamiento(quina_amarilla,menstruacion_irregular).
tratamiento(sabina,menstruacion_irregular).
tratamiento(artemisa,menstruacion_irregular).
tratamiento(hamamelis,metrorragia).
tratamiento(zoapatle,metrorragia).
tratamiento(perejil,metrorragia).
tratamiento(clavo,muelas).
tratamiento(hiedra,muelas_dolor).
tratamiento(ortiga,nariz_hemorragia).
tratamiento(cola_de_caballo,nariz_hemorragia).
tratamiento(ruda,nariz_hemorragia).
tratamiento(eucalipto,nariz_hemorragia).
tratamiento(anis,nauseas).
tratamiento(ajenjo,nauseas).
tratamiento(menta,nauseas).
tratamiento(salvia,nauseas).
tratamiento(manzanilla,neuralgias).
tratamiento(menta,neuralgias).
tratamiento(valeriana,neuralgias).
tratamiento(boldo,neuralgias).
tratamiento(pasiflora,neurastenia).
tratamiento(te_negro,neurastenia).
tratamiento(mate,neurastenia).
tratamiento(valeriana,neurastenia).
tratamiento(linaza,nefritis).
tratamiento(grama,nefritis).
tratamiento(cebada,nefritis).
tratamiento(llanten,nefritis).
tratamiento(doradillas,nefritis).
tratamiento(esparrago,nefritis).
tratamiento(ruda,nefritis).
tratamiento(toronjil,obesidad).
tratamiento(marrubio,obesidad).
tratamiento(limon,obesidad).
tratamiento(malva,obesidad).
tratamiento(esparrago,obesidad).
tratamiento(boldo,oidos).
tratamiento(aceite_de_oliva,oidos).
tratamiento(llanten,oidos).
tratamiento(hiedra,oidos).
tratamiento(manzanilla,ojos).
tratamiento(limon,ojos).
tratamiento(llanten,ojos).
tratamiento(salvia,ojos).
tratamiento(ruda,ojos).
tratamiento(rosal,ojos).
tratamiento(ajenjo,paludismo).
tratamiento(quina,paludismo).
tratamiento(berro,pecas).
tratamiento(genciana,pecas).
tratamiento(rabano,pecas).
tratamiento(papaya,pecas).
tratamiento(laurel,pies_olorosos).
tratamiento(encina,pies_olorosos).
tratamiento(miel,piquetes_de_abeja).
tratamiento(perejil,piquetes_de_abeja).
tratamiento(cebolla,piquetes_de_abeja).
tratamiento(puerco,piquetes_de_abeja).
tratamiento(fresno,piquetes_de_araña).
tratamiento(ipecacuana,piquetes_de_araña).
tratamiento(alcanfor,piquetes_de_mosco).
tratamiento(perejil,piquetes_de_mosco).
tratamiento(hamamelis,piquetes_de_mosco).
tratamiento(anagalide,piquetes_de_vibora).
tratamiento(jengibre,pleuresia).
tratamiento(linaza,pleuresia).
tratamiento(cardo,pleuresia).
tratamiento(girasol,pleuresia).
tratamiento(ipecacuana,piorrea).
tratamiento(cola_de_caballo,prostata).
tratamiento(eucalipto,pulmonia).
tratamiento(ocote,pulmonia).
tratamiento(gordolobo,pulmonia).
tratamiento(borraja,pulmonia).
tratamiento(sauco,pulmonia).
tratamiento(linaza,quemaduras).
tratamiento(cebolla,quemaduras).
tratamiento(hiedra,quemaduras).
tratamiento(gordolobo,quemaduras).
tratamiento(nogal,raquitismo).
tratamiento(ajo,reumatismo).
tratamiento(apio,reumatismo).
tratamiento(borreja,reumatismo).
tratamiento(gobernadora,reumatismo).
tratamiento(pino,reumatismo).
tratamiento(romero,reumatismo).
tratamiento(sanguinaria,reumatismo).
tratamiento(marrubio,reumatismo).
tratamiento(tabaco,reumatismo).
tratamiento(cabellos_de_elote,riñones).
tratamiento(cola_de_caballo,riñones).
tratamiento(apio,riñones).
tratamiento(eucalipto,ronquera).
tratamiento(pino,ronquera).
tratamiento(gordolobo,ronquera).
tratamiento(ajo,sabañones).
tratamiento(cebolla,sabañones).
tratamiento(estafiate,san_vito).
tratamiento(valeriana,san_vito).
tratamiento(borraja,sarampion).
tratamiento(ortiga,sarampion).
tratamiento(sauco,sarampion).
tratamiento(ajo,sarna).
tratamiento(alcanfor,sarna).
tratamiento(menta,sarna).
tratamiento(tornillo,sarna).
tratamiento(romero,sarna).
tratamiento(encina,sarpullido).
tratamiento(savia,sarpullido).
tratamiento(tila,sarpullido).
tratamiento(limon,sed).
tratamiento(tamarindo,sed).
tratamiento(pirul,sed).
tratamiento(semilla_de_calabaza,solitaria).
tratamiento(raiz_de_granado_agrio,solitaria).
tratamiento(coquito_de_aceite,solitaria).
tratamiento(helecho_macho,solitaria).
tratamiento(encina,sudoracion_excesiva).
tratamiento(alcanfor,tifoidea).
tratamiento(borraja,tifoidea).
tratamiento(quina,tifoidea).
tratamiento(canela,tifoidea).
tratamiento(romero,tifoidea).
tratamiento(salvia,tifoidea).
tratamiento(berro,tiña).
tratamiento(tila,tiña).
tratamiento(tamarindo,tiña).
tratamiento(salvia,tiña).
tratamiento(eucalipto,tos).
tratamiento(capulin,tos).
tratamiento(cedron,tos).
tratamiento(salvia,tos).
tratamiento(malva,tos).
tratamiento(marrubio,tos).
tratamiento(gelsemio,tos_ferina).
tratamiento(quina,tos_ferina).
tratamiento(rabano,tos_ferina).
tratamiento(violeta,tos_ferina).
tratamiento(jugo_de_vastago_de_platano_morado,tuberculosis).
tratamiento(mastuerzo,tuberculosis).
tratamiento(berro,tuberculosis).
tratamiento(ajo,tuberculosis).
tratamiento(eucalipto,tuberculosis).
tratamiento(pirul,tuberculosis).
tratamiento(pino,tuberculosis).
tratamiento(roble,tuberculosis).
tratamiento(cacahuate,ulcera).
tratamiento(sanguinaria,ulcera).
tratamiento(cola_de_caballo,ulcera).
tratamiento(girasol,ulcera).
tratamiento(limon,urticaria).
tratamiento(ruibarbo,urticaria).
tratamiento(hamamelis,varices).
tratamiento(castaño_de_indias,varices).
tratamiento(llanten,varices).
tratamiento(toronjil,varices).
tratamiento(apio,vejiga).
tratamiento(cipres,vejiga).
tratamiento(cola_de_caballo,vejiga).
tratamiento(ortiga,vejiga).
tratamiento(malva,vejiga).
tratamiento(leche_de_higuera,verrugas).
tratamiento(cebolla,verrugas).
tratamiento(nogal,verrugas).
tratamiento(albahaca,vertigos).
tratamiento(espino,vertigos).
tratamiento(menta,vomitos).
tratamiento(tila,vomitos).
tratamiento(marrubio,vomitos).
tratamiento(valeriana,vomitos).
tratamiento(salvia,vomitos).
tratamiento(cilantro,voz).
tratamiento(limon,voz).
tratamiento(ajo,voz).
tratamiento(pino,voz).
tratamiento(alfalfa,falta_de_vitaminas).
tratamiento(espinacas,falta_de_vitaminas).
tratamiento(acelga,falta_de_vitaminas).
tratamiento(berro,falta_de_vitaminas).
tratamiento(cebolla,falta_de_vitaminas).
tratamiento(limon,falta_de_vitaminas).
tratamiento(zanahoria,falta_de_vitaminas).
tratamiento(aceite_de_bacalao,falta_de_vitaminas).

tratamiento(mangle, estreñimiento).
tratamiento(mangle, vias_biliares).

%El medicamento X proviene de la planta Y%
medicamento(morfina,opio).
medicamento(codeína,opio).
medicamento(digitalina,digital).
medicamento(tónico_cardiaco,digital).
medicamento(emetina,ipeca).
medicamento(estricnina,nuez_vómica).
medicamento(veratrina,eléboro_blanco).
medicamento(colquicina,colchico).
medicamento(atropina,belladona).
medicamento(quinina,quina).
medicamento(teobromina,cacao).
medicamento(esparteína,retama).
medicamento(cocaína,coca).
medicamento(mescalina,peyote).
medicamento(efedrina,efedra).
medicamento(hormonas,barbasco).
medicamento(letenurina,nenúfar_amarillo).
medicamento(diosponina,ñame).
medicamento(tauremisina,artemisa).
medicamento(olitorisida,semilla_de_yute).
medicamento(ácido_lisérgico,toloache).
medicamento(eucaliptol,eucalipto).
medicamento(vitamina_c,rosal).
medicamento(quercitrina,rosal).

%El concepto X significa Y%
concepto(afrodisiaca,que_excita_el_apetito_sexual).
concepto(analgésica,que_quita_o_modera_el_dolor).
concepto(anestésica,que_insensibiliza_el_cuerpo).
concepto(antidiarreica,que_controla_diarreas_o_deposiciones).
concepto(antiespasmódica,que_controla_espasmos_nerviosos).
concepto(antiflogística,que_actúa_contra_las_inflamaciones).
concepto(antipirética,que_quita_o_disminuye_la_fiebre).
concepto(antiséptica,que_mata_los_tejidos).
concepto(aperitiva,que_produce_apetito).
concepto(astringente,que_hace_contraer_los_tejidos).
concepto(carminativa,que_evita_la_formación_de_gases_o_provoca_su_expulsión).
concepto(colagoga,que_ayuda_a_expulsar_la_bilis).
concepto(depurativa,que_limpia_y_purifica_la_sangre).
concepto(diaforética,que_provoca_sudar_como_cochino).
concepto(digestiva,que_favorece_la_digestión).
concepto(diurética,que_provoca_la_orina).
concepto(emética,que_provoca_náuseas_y_vómitos).
concepto(emenagoga,que_activa_la_menstruación).
concepto(estupefaciente,que_aquieta_duerme_o_atonta).
concepto(expectorante,que_expulsa_flemas_y_mucosidades).
concepto(hemostática,que_corta_o_detiene_hemorragias).
concepto(hepática,que_ayuda_al_hígado).
concepto(iatrogenia,enfermedad_provocada_por_las_medicinas).
concepto(laxante,que_purga_sin_provocar_diarrea).
concepto(pectoral,que_ayuda_al_pecho).
concepto(sedante,que_calma_dolores_intestinales).
concepto(tónica,que_da_fuerza_al_organismo).
concepto(tóxica,que_es_venenosa).
concepto(vermífuga,que_expulsa_gusanos_intestinales).
concepto(vulneraria,que_cura_llagas_y_heridas).

%Las plantas se pueden consumir de X forma%
consumo(cocimiento).
consumo(infusión).
consumo(maceración).
consumo(jarabe).
consumo(tintura).
consumo(jugo).
consumo(horchata).

%Nombre en latin de la planta X%
nombre_latin(rhizophora_mangle, mangle).
nombre_latin(matricaria_chamomilla, manzanilla).
nombre_latin(marrubium_vulgare, marrubio).

